version: '3.8'

services:
  vision_node:
    build:
      context: .

    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/catkin_ws/src/submarine
    ports:
      - "8000:8000"  # Maps host port 8000 to container port 8000
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]
